services:
    backend:
        image: ghcr.io/arw6329/sql-playground-backend
        build: ./backend
        ports:
            - 12345:8080
        secrets:
            - postgres12pwd
            - postgres13pwd
            - postgres14pwd
            - postgres15pwd
            - postgres16pwd
            - mysql8.4pwd
            - mysql8.0pwd
            - oracle23aipwd
            - oracle21cpwd
        environment:
            - ENABLED_DBS=${ENABLED_DBS:-*}
            - FRONTEND_ORIGIN=http://localhost:4321
        volumes:
            - csv_upload_storage:/csv

    postgres12:
        image: postgres:12
        restart: always
        secrets:
            - postgres12pwd
        environment:
            POSTGRES_PASSWORD_FILE: /run/secrets/postgres12pwd
            PGPORT: 8000
        profiles:
            - postgres12
    postgres13:
        image: postgres:13
        restart: always
        secrets:
            - postgres13pwd
        environment:
            POSTGRES_PASSWORD_FILE: /run/secrets/postgres13pwd
            PGPORT: 8000
        profiles:
            - postgres13
    postgres14:
        image: postgres:14
        restart: always
        secrets:
            - postgres14pwd
        environment:
            POSTGRES_PASSWORD_FILE: /run/secrets/postgres14pwd
            PGPORT: 8000
        profiles:
            - postgres14
    postgres15:
        image: postgres:15
        restart: always
        secrets:
            - postgres15pwd
        environment:
            POSTGRES_PASSWORD_FILE: /run/secrets/postgres15pwd
            PGPORT: 8000
        profiles:
            - postgres15
    postgres16:
        image: postgres:16
        restart: always
        secrets:
            - postgres16pwd
        environment:
            POSTGRES_PASSWORD_FILE: /run/secrets/postgres16pwd
            PGPORT: 8000
        profiles:
            - postgres16
    
    mysql8.4:
        image: mysql:8.4
        restart: always
        secrets:
            - mysql8.4pwd
        environment:
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql8.4pwd
        profiles:
            - mysql8.4
    mysql8.0:
        image: mysql:8.0
        restart: always
        secrets:
            - mysql8.0pwd
        environment:
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql8.0pwd
        profiles:
            - mysql8.0

    oracle23ai:
        image: container-registry.oracle.com/database/free:23.5.0.0
        restart: always
        secrets:
            - source: oracle23aipwd
              target: oracle_pwd
        environment:
            DECRYPT_PWD_FILE: decryptPasswordFixed.sh
        profiles:
            - oracle23ai
        configs:
            - source: oracle_set_pwd_script
              target: /opt/oracle/decryptPasswordFixed.sh
              uid: '54321'
              gid: '54321'
              mode: 0550
            - source: oracle_enable_omf_script
              target: /opt/oracle/scripts/startup/enableOMF.sql
              uid: '54321'
              gid: '54321'
              mode: 0444
        
    oracle21c:
        image: container-registry.oracle.com/database/free:23.5.0.0
        restart: always
        secrets:
            - source: oracle21cpwd
              target: oracle_pwd
        environment:
            DECRYPT_PWD_FILE: decryptPasswordFixed.sh
        profiles:
            - oracle21c
        configs:
            - source: oracle_set_pwd_script
              target: /opt/oracle/decryptPasswordFixed.sh
              uid: '54321'
              gid: '54321'
              mode: 0550
            - source: oracle_enable_omf_script
              target: /opt/oracle/scripts/startup/enableOMF.sql
              uid: '54321'
              gid: '54321'
              mode: 0444

secrets:
    postgres12pwd:
        file: secrets/postgres12pwd.txt
    postgres13pwd:
        file: secrets/postgres13pwd.txt
    postgres14pwd:
        file: secrets/postgres14pwd.txt
    postgres15pwd:
        file: secrets/postgres15pwd.txt
    postgres16pwd:
        file: secrets/postgres16pwd.txt
    mysql8.4pwd:
        file: secrets/mysql8.4pwd.txt
    mysql8.0pwd:
        file: secrets/mysql8.0pwd.txt
    oracle23aipwd:
        file: secrets/oracle23aipwd.txt
    oracle21cpwd:
        file: secrets/oracle21cpwd.txt

configs:
    oracle_set_pwd_script:
        content: 'cat /run/secrets/oracle_pwd'
    oracle_enable_omf_script:
        content: "ALTER SYSTEM SET DB_CREATE_FILE_DEST='/opt/oracle/oradata';"

volumes:
    csv_upload_storage:
